groups:
  arm:
    operating_mode: velocity
    profile_type: time
    profile_velocity: 2000
    profile_acceleration: 300
    torque_enable: true

singles:
  gripper:
    operating_mode: pwm
    torque_enable: true
